### ISSUE TITLE
Implement catalog subcommand

### ISSUE THREAD

**Issue by kylebittinger** [scottdaniel/sequence_db#8]

**Comment by scottdaniel** [comment]
- [x]  pull in Vince’s changes and cleanup
- [ ]  implement catalog subcommand:
    - [x]  set directory and catalog name
    - [x]  search through directory for sequence files
    - [ ]  use extract function to get metadata
    - [ ]  build json from extracted metadata

**Comment by scottdaniel** [comment]
Implemented with commit e391ef
